language: bash
python:
  - "2.7"

services: docker

install:
  - docker pull smartslab/ci_openipsl

script:
  - sudo chown 1000 $(pwd)
  - docker run -i -t -v $(pwd):/OpenIPSL smartslab/ci_openipsl sh /OpenIPSL/CI/changeUser.sh
