language: bash
python:
  - "2.7"

services: docker

install:
  - docker pull smartslab/openipsl

script:
  - docker run -i -t -v $(pwd):/OpenIPSL -u smartslab smartslab/openipsl sh -c "python /OpenIPSL/CI/syntaxCheck.py"
