language: bash
python:
  - "2.7"

services: docker

install:
  - docker pull smartslab/openipsl:addDockerFile

script:
  - docker run -i -t -v $(pwd):/OpenIPSL smartslab/openipsl:addDockerFile sh /OpenIPSL/CI/changeUser.sh
