language: bash
python:
  - "2.7"

services: docker

install:
  - docker pull smartslab/openipsl:test

script:
  - docker run -i -t -v $(pwd):/OpenIPSL smartslab/openipsl:test sh -c "python /OpenIPSL/CI/syntaxCheck.py"
